In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("ambulance6.csv")
df.head()

,Age,Gender,Injury_Type,BP,Heart_Rate,SpO2,Consciousness,Temperature,Pregnant,Diabetic,Cardiac_History,Severity,Required_Facilities,Doctor_Type,Hospital_Type
0,48,0,2,133.518910,72.939989,94.817402,0,97.429176,1,0,0,Low,Emergency Care,Trauma Surgeon,Trauma Center
1,69,0,0,146.769632,86.228594,89.446971,0,98.728153,0,0,0,Low,Emergency Care,Cardiologist,Cardiac Hospital
2,26,0,0,94.381422,81.237599,90.108566,1,98.212821,0,0,0,Medium,Emergency Care,Cardiologist,Cardiac Hospital
3,68,1,4,111.609522,61.996906,97.064742,0,96.679036,0,0,0,Low,Emergency Care,General Physician,General Hospital
4,84,1,4,125.597425,92.032773,99.547516,0,98.860740,0,0,0,Low,Emergency Care,General Physician,General Hospital


In [3]:
print(df.dtypes)
print(df.isnull().sum())

Age                      int64
Gender                   int64
Injury_Type              int64
BP                     float64
Heart_Rate             float64
SpO2                   float64
Consciousness            int64
Temperature            float64
Pregnant                 int64
Diabetic                 int64
Cardiac_History          int64
Severity                object
Required_Facilities     object
Doctor_Type             object
Hospital_Type           object
dtype: object
Age                    0
Gender                 0
Injury_Type            0
BP                     0
Heart_Rate             0
SpO2                   0
Consciousness          0
Temperature            0
Pregnant               0
Diabetic               0
Cardiac_History        0
Severity               0
Required_Facilities    0
Doctor_Type            0
Hospital_Type          0
dtype: int64


In [4]:
X = df.drop(['Severity','Required_Facilities','Doctor_Type','Hospital_Type'], axis=1)
y = df['Severity']

In [5]:
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [7]:
model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.08,
    max_depth=5
)

model.fit(X_train, y_train)

,loss,'log_loss'
,learning_rate,0.08
,n_estimators,200
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,5
,min_impurity_decrease,0.0
,init,None


In [8]:
y_pred = model.predict(X_test)

In [9]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.942

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.84      0.87        90
           1       0.99      0.94      0.96      5612
           2       0.77      0.97      0.86      1298

    accuracy                           0.94      7000
   macro avg       0.89      0.92      0.90      7000
weighted avg       0.95      0.94      0.94      7000


Confusion Matrix:
 [[  76    0   14]
 [   0 5261  351]
 [   8   33 1257]]


In [10]:
X = df.drop(['Severity','Required_Facilities','Doctor_Type','Hospital_Type'], axis=1)
y1 = df['Required_Facilities']

In [11]:
le1 = LabelEncoder()
y1 = le1.fit_transform(y1)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y1, test_size=0.2, random_state=42
)

In [13]:
model1 = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.08,
    max_depth=5
)

model1.fit(X_train, y_train)

,loss,'log_loss'
,learning_rate,0.08
,n_estimators,200
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,5
,min_impurity_decrease,0.0
,init,None


In [14]:
y_pred1 = model1.predict(X_test)

In [15]:
print("Accuracy:", accuracy_score(y_test, y_pred1))

print("\nClassification Report:\n", classification_report(y_test, y_pred1))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred1))

Accuracy: 0.8994285714285715

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.91      0.94      5888
           1       0.63      0.84      0.72      1088
           2       0.17      0.04      0.07        24

    accuracy                           0.90      7000
   macro avg       0.59      0.60      0.58      7000
weighted avg       0.91      0.90      0.90      7000


Confusion Matrix:
 [[5381  507    0]
 [ 169  914    5]
 [   0   23    1]]


In [17]:

severity_pred = model.predict(X_test)

severity_pred = le.inverse_transform(severity_pred)



facility_pred = model1.predict(X_test)

facility_pred = le1.inverse_transform(facility_pred)

In [18]:
def get_doctor(injury, severity):
    
    if injury == 0:  # Chest Pain type
        return "Cardiologist"
    
    elif injury == 1:  # Neuro cases
        return "Neurologist"
    
    elif injury == 2:  # Accident / trauma
        return "Trauma Surgeon"
    
    else:
        if severity == "High":
            return "Specialist"
        return "General Physician"

In [19]:
def get_hospital(doctor):
    
    if doctor == "Cardiologist":
        return "Cardiac Hospital"
    
    elif doctor == "Neurologist":
        return "Neuro Center"
    
    elif doctor == "Trauma Surgeon":
        return "Trauma Center"
    
    else:
        return "General Hospital"

In [20]:
i = 0  # any index

injury = X_test.iloc[i]['Injury_Type']

severity = severity_pred[i]
facility = facility_pred[i]

doctor = get_doctor(injury, severity)
hospital = get_hospital(doctor)

result = {
    "Severity": severity,
    "Facility": facility,
    "Doctor": doctor,
    "Hospital": hospital
}

print(result)

{'Severity': 'Low', 'Facility': 'Emergency Care', 'Doctor': 'Neurologist', 'Hospital': 'Neuro Center'}


In [21]:
def get_first_aid(injury):
    
    if injury == 0:  # Chest Pain
        return [
            "Make the person sit and stay calm",
            "Loosen tight clothes",
            "Give aspirin if not allergic",
            "Avoid physical movement"
        ]
    
    elif injury == 1:  # Stroke / Seizure
        return [
            "Lay patient on side",
            "Do NOT put anything in mouth",
            "Clear surroundings to prevent injury",
            "Check breathing"
        ]
    
    elif injury == 2:  # Accident / Trauma
        return [
            "Check for bleeding",
            "Apply firm pressure on wounds",
            "Keep patient still",
            "Do not move neck or spine"
        ]
    
    elif injury == 3:  # Burn
        return [
            "Cool the burn with running water",
            "Do NOT apply ice",
            "Cover with clean cloth",
            "Do not burst blisters"
        ]
    
    else:  # General illness
        return [
            "Let the patient rest",
            "Give water if conscious",
            "Monitor condition",
            "Seek medical help if worse"
        ]

In [23]:
injury = "Chest Pain"   #user_input_injury   # from UI

first_aid = get_first_aid(injury)

print("First Aid Instructions:")
for step in first_aid:
    print("-", step)

First Aid Instructions:
- Let the patient rest
- Give water if conscious
- Monitor condition
- Seek medical help if worse
